# Generated by Django 4.1.5 on 2023-03-09 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
